version: "3"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./work-dir/:/home/node/app
    ports:
      - "3000:3000"
#    command: bash -c "cd ./api && tail -f test.txt"
    command: bash -c "cd ./api && DEBUG=api:* yarn dev"
    links:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
